export const STAGE3_SELECTION_DURATION_SECONDS = 15;
export const STAGE3_ANSWER_DURATION_SECONDS = 20;
export const STAGE3_REVEAL_DURATION_SECONDS = 10;
export const STAGE3_SELECTION_TIMEOUT_PENALTY = -5;
